name: macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install some package
        run: ./test emacs vlc

      - name: Test installed package
        run: brew test emacs
      
        
