name: macOS

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install some packages
        run: ./test

      - name: Test installed brew
        run: brew test ack

      - name: Test installed cask
        run: brew test gpg-suite

      - name: Test cask installed through Brewfile
        run: brew test firefox

      - name: Test brew installed through Brewfile
        run: brew test jq
