name: macOS

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install some packages
        run: ./test

      - name: Test installed brew
        run: brew ls ack

      - name: Test installed cask
        run: brew ls --cask gpg-suite

      - name: Test cask installed through Brewfile
        run: brew ls --cask firefox

      - name: Test brew installed through Brewfile
        run: brew ls jq
